services:
  server:
    image: 'p2sr-bot'
    build:
      context: .
    container_name: 'p2sr-bot'
    restart: always
    volumes:
      - /var/bot/kv:/app/kv
      - /var/bot/p2sr.key:/app/p2sr.key
