[book]
authors = ["NeKz"]
language = "en"
multilingual = false
src = "src"
title = "NeKzBot"

[output.html]
additional-css = ["doc.css"]
cname = "bot.nekz.me"
git-repository-url = "https://github.com/NeKzor/tem"
git-repository-icon = "fa-github"

[output.html.search]
enable = false

[output.html.print]
enable = false
